version: "3.7"
services:
    www:
        build: ./
        volumes:
            - ./:/app
            - /app/node_modules
        ports:
            - 5008:5008
        environment:
            - PORT=5008
            - PRODUCTION=1
            - APIPORT=8080
            - APIURL=http://bits.com.kw
